const pdf = require('html-pdf');
const fs = require('fs');
const path = require('path');

const generatePDF = (data, callback) => {
    // Create HTML template
    const htmlTemplate = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>${data.title}</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #333; text-align: center; }
                h2 { color: #444; border-bottom: 1px solid #eee; padding-bottom: 5px; }
                .report-info { margin-bottom: 20px; font-size: 14px; color: #666; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #f2f2f2; }
                .chart-placeholder { 
                    background-color: #f9f9f9; 
                    border: 1px dashed #ccc; 
                    padding: 20px; 
                    text-align: center; 
                    margin: 20px 0;
                }
                .footer { 
                    margin-top: 30px; 
                    font-size: 12px; 
                    color: #999; 
                    text-align: center; 
                    border-top: 1px solid #eee;
                    padding-top: 10px;
                }
            </style>
        </head>
        <body>
            <h1>${data.title}</h1>
            <div class="report-info">
                Generated on: ${data.date}
            </div>
            
            <h2>Summary</h2>
            <table>
                ${data.data.map(item => `
                    <tr>
                        <td><strong>${item.label}</strong></td>
                        <td>${item.value}</td>
                    </tr>
                `).join('')}
            </table>
            
            ${data.chartData ? `
                <h2>Charts</h2>
                <div class="chart-placeholder">
                    Chart: ${JSON.stringify(data.chartData.labels)}<br>
                    Data: ${JSON.stringify(data.chartData.datasets)}
                </div>
            ` : ''}
            
            ${data.topProducts ? `
                <h2>Top Products</h2>
                <table>
                    <tr>
                        <th>Product</th>
                        <th>Units Sold</th>
                        <th>Revenue</th>
                    </tr>
                    ${data.topProducts.map(product => `
                        <tr>
                            <td>${product.name}</td>
                            <td>${product.sold}</td>
                            <td>${product.revenue}</td>
                        </tr>
                    `).join('')}
                </table>
            ` : ''}
            
            <div class="footer">
                Report generated by Y-Balash Admin Dashboard
            </div>
        </body>
        </html>
    `;

    const options = {
        format: 'A4',
        orientation: 'portrait',
        border: {
            top: '20px',
            right: '20px',
            bottom: '20px',
            left: '20px'
        }
    };

    // Generate PDF
    pdf.create(htmlTemplate, options).toBuffer((err, buffer) => {
        if (err) {
            return callback(err);
        }
        callback(null, buffer);
    });
};

module.exports = {
    generatePDF
};